### ISSUE TITLE
Deciding project structure

### ISSUE THREAD

**Issue by SiddharthSham** [SiddharthSham/cssify#1]
Hey, so for initial segregation of functionality I thought it makes sense to split the project into a front-end, back-end and scss modules.

Proposed folder structure:

cssify
--backend
--frontend
--scss

**Comment by stealthanthrax** [comment]
@SiddharthSham , the `scss` folder for the libraries of the css framework, right?

**Comment by SiddharthSham** [comment]
Yes, essentially.

**Comment by stealthanthrax** [comment]
Alright then. Will push a basic pr in an hour.

**Comment by SiddharthSham** [comment]
Alright, looks good. I'll close this issue. 👍
