### ISSUE TITLE
Create layouts for the generated styles 

### ISSUE THREAD

**Issue by stealthanthrax** [SiddharthSham/cssify#4]
We would require a layout for the user to preview the generated styles and then review his/her selections.

**Comment by ani4aniket** [comment]
@stealthanthrax, I have merged the basic testing preview with user selection/input.

**Comment by stealthanthrax** [comment]
Good job @ani4aniket 🔥 . We'll close the issue once we complete the layout.

**Comment by ani4aniket** [comment]
Creating a better version stay tuned 😊😉
